import os, os.path
import lsst.SConsUtils as scons
import distutils.sysconfig


Import("env")

ext_libs = ["gsl", "gslcblas", "pex_exceptions"]

common_libs = ['../Detection.o', '../common.o', '../collapseTrackletsAndPostfilters/TrackletCollapser.o',
               '../collapseTrackletsAndPostfilters/rmsLineFit.o']

env.Library('detectionProximity', common_libs + ['detectionProximity.cc'])

env.Program('detectionProximity-unitTests', ['detectionProximityUnitTests.cc', 
                                             'detectionProximity.o'] + common_libs, 
            LIBS=ext_libs)

