# -*- python -*-
# jmyers, 9/11/09 


Import("env")
Import("common_libs")
#Import("ext_libs")

env.Library('../../lib/detectionProximity', common_libs + ['detectionProximity.cc'],
            LIBS=filter(lambda x: x != "mops_daymops", env.getlibs("mops_daymops")))

env.Program('../../tests/detectionProximity-unitTests', ['detectionProximityUnitTests.cc', 
                                                         'detectionProximity.o'] + common_libs,
            LIBS=filter(lambda x: x != "mops_daymops", env.getlibs("mops_daymops")))

