import os, os.path
import lsst.SConsUtils as scons
import distutils.sysconfig

doExtras = True


Import("env")




common_libs = ['../common.o', '../collapseTrackletsAndPostfilters/SubsetRemover.o', '../Detection.o', 
	      '../collapseTrackletsAndPostfilters/TrackletCollapser.o', 
               '../collapseTrackletsAndPostfilters/rmsLineFit.o']

ext_libs = ["gsl", "gslcblas", "pex_exceptions"]
		      

env.Library('linkTracklets', ['linkTracklets.cc'] + common_libs)

env.Program('linkTracklets-unitTests', ['linkTracklets-unittests.cc', 'linkTracklets.o'] + common_libs, 
				       LIBS=ext_libs)

env.Program('linkTracklets', ['linkTrackletsMain.cc', 'linkTracklets.o'] + common_libs,
				       LIBS=ext_libs)




if doExtras:
    env.Program('findLinkableObjects', ['findLinkableObjects.cc'] + common_libs, 
				       LIBS=ext_libs)
