# -*- python -*-
# jmyers, 9/11/09 


Import("env")
Import("common_libs")
#Import("ext_libs")

env.Library('../../lib/Field', 'Field.cc', 
            LIBS=filter(lambda x: x != "mops_daymops", env.getlibs("mops_daymops")))

env.Library('../../lib/fieldProximity', common_libs + ['fieldProximity.cc', 'Field'],
            LIBS=filter(lambda x: x != "mops_daymops", env.getlibs("mops_daymops")))

env.Program('../../tests/fieldProximity-unitTests', ['fieldProximityUnitTests.cc', 'fieldProximity.o', 'Field'] + common_libs,
            LIBS=filter(lambda x: x != "mops_daymops", env.getlibs("mops_daymops")))


