# -*- python -*-
# jmyers, 9/11/09 


Import("env")
Import("common_libs")
Import("ext_libs")



env.Library('../../lib/findTracklets', ['findTracklets.cc'] + common_libs)

env.Program('../../tests/findTracklets-unitTests', 
            ['findTracklets-unittests.cc', 'findTracklets'] +  common_libs, 
            LIBS=ext_libs)

env.Program('../../bin/findTracklets', 
            ['findTrackletsMain.cc', 'findTracklets'] + common_libs,
            LIBS=ext_libs)


#env.LoadableModuleIncomplete("_findTracklets", Split("findTracklets.i"), 
#                             LIBS=env.getlibs(["pex_exceptions"]))
