# -*- python -*-
# jmyers, 9/11/09 


Import("env")
Import("common_libs")
Import("ext_libs")




env.Program('collapseTracklets-unittests', ['unitTests.cc', 'collapseTracklets'] + common_libs, LIBS=ext_libs)

ct = env.Library('collapseTracklets', ['collapseTracklets.cc'] + common_libs, LIBS=ext_libs)

env.Program('collapseTracklets', ['collapseTrackletsMain.cc', ct] + common_libs, 
            LIBS=ext_libs)

env.Program('purifyTracklets', ['purifyTracklets.cc'] + common_libs, LIBS=ext_libs)



#env.CheckSwig("python", ilang="c++")

#env.LoadableModuleIncomplete("_TrackletCollapser", Split("TrackletCollapser.i"), 
#                             LIBS=env.getlibs(["pex_exceptions"]))
