import lsst.SConsUtils as scons

Import("env")



ext_libs = ["gsl", "gslcblas", "pex_exceptions"]
		      
commonStuff = ['../common', 'SubsetRemover', '../Detection', 
	      'TrackletCollapser', 'rmsLineFit']
common_libs = []
for lib in commonStuff:
    common_libs.append(lib+'.o')



env.Program('collapseTracklets-unittests', ['unitTests.cc'] + common_libs, LIBS=ext_libs)
env.Program('collapseTracklets', ['collapseTrackletsMain.cc'] + common_libs, LIBS=ext_libs)
env.Program('removeSubsets', ['removeSubsetsMain.cc'] + common_libs, LIBS=ext_libs)
env.Program('purifyTracklets', ['purifyTracklets.cc'] + common_libs, LIBS=ext_libs)
