import os, os.path
import lsst.SConsUtils as scons
import distutils.sysconfig


env = scons.makeEnv("trackingLib",
    r"1.0",
    [["boost", "boost/test/included/unit_test.hpp"],
    ["pex_exceptions", "lsst/pex/exceptions/Exception.h lsst/pex/exceptions/Runtime.h", "pex_exceptions:C++"],
    ["gsl", "gsl/gsl_fit.h", "gslcblas gsl:C++"]
    ])


ext_libs = ["gsl", "gslcblas", "pex_exceptions"]
		      
commonStuff = ['common', 'collapseTrackletsAndPostfilters/SubsetRemover', 'Detection', 
	      'collapseTrackletsAndPostfilters/TrackletCollapser', 'collapseTrackletsAndPostfilters/rmsLineFit',
               'Orbit']
common_libs = []



for lib in commonStuff:
    env.StaticLibrary(lib, lib+'.cc')
    env.Library(lib, lib+'.cc')
    common_libs.append(lib+'.o')

commonStuff = ['common', 'collapseTrackletsAndPostfilters/SubsetRemover', 'Detection', 
	      'collapseTrackletsAndPostfilters/TrackletCollapser', 'collapseTrackletsAndPostfilters/rmsLineFit']
common_libs = []

for lib in commonStuff:
    env.StaticLibrary(lib, lib+'.cc')
    env.Library(lib, lib+'.cc')
    common_libs.append(lib+'.o')

env.Program('utilities-unittests', ['generalUnitTests.cc'] + common_libs, LIBS=ext_libs)



SConscript('findTracklets/SConscript')
SConscript('collapseTrackletsAndPostfilters/SConscript')
SConscript('linkTracklets/SConscript')

SConscript('detectionProximity/SConscript')
SConscript('fieldProximity/SConscript')
SConscript('orbitProximity/SConscript')
