import os, os.path
import lsst.SConsUtils as scons
import distutils.sysconfig


Import("env")


ext_libs = ["gsl", "gslcblas", "pex_exceptions"]

common_libs = ['../Detection.o', '../common.o', '../collapseTrackletsAndPostfilters/TrackletCollapser.o',
               '../collapseTrackletsAndPostfilters/rmsLineFit.o', '../Orbit.o']

env.Library('orbitProximity', common_libs + ['orbitProximity.cc'])

env.Program('orbitProximity', ['orbitProximityMain.cc', 
				 'orbitProximity.o'] + common_libs, 
            LIBS=ext_libs)

env.Program('orbitProximity-unitTests', ['orbitProximityUnitTests.cc', 
					 'orbitProximity.o'] + common_libs, 
            LIBS=ext_libs)


