# -*- python -*-
# jmyers, 9/11/09 


Import("env")
Import("common_libs")
#Import("ext_libs")

env.Library('../../lib/orbitProximity', common_libs + ['orbitProximity.cc'], 
            LIBS=filter(lambda x: x != "mops_daymops", env.getlibs("mops_daymops")))

env.Program('../../bin/orbitProximity', ['orbitProximityMain.cc', 
                                         'orbitProximity.o'] + common_libs,
            LIBS=filter(lambda x: x != "mops_daymops", env.getlibs("mops_daymops")))

env.Program('../../tests/orbitProximity-unitTests', ['orbitProximityUnitTests.cc', 
					 'orbitProximity.o'] + common_libs,
            LIBS=filter(lambda x: x != "mops_daymops", env.getlibs("mops_daymops")))


